### ISSUE TITLE
诚邀大神加入 Chisel 中文社区

### ISSUE THREAD

**Issue by itviewer** [sequencer/diplomacy#9]
搭了个学习 Chisel 相关的中文社区，诚邀大神入伙，要是能抽空在这里
https://www.easysoc.cn/topics/node29
分享些 Diplomacy 设计的精髓，将不胜感激:handshake:

**Comment by sequencer** [comment]
Thank you for invitation!
But I think Chips Alliance GitHub and Maillist are enough for a community usages, so I will mainly work and share here. 
If you have any questions or improvements to diplomacy, issues and PRs are welcomed!
Until we polish these framework so mature that can be released, I will work on improvements to documentation tests, and writing some blogs, but currently, we may have no enough time to do so.
